name: "@malolk"
description: "Liu Kai's blog"
meta_description: "@malolk Liu Kai's blog"

permalink: /:year/:month/:day/:title.html
paginate: 15
markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
imgurl: "https://github.com/malolk/malolk.github.io/tree/master/_images"
domain_name: 'http://malolk.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            "http://malolk.com"
author:         "Liu Kai"
