name: "@malolk"
description: "Liu Kai's blog"
meta_description: "@malolk Liu Kai's blog"

permalink: /:year/:month/:day/:title.html
paginate: 15
markdown: kramdown
highlighter: pygments
logo: false
baseurl: ""
domain_name: 'http://malolk.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            "http://malolk.com"
author:         "Liu Kai"
